# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sha-GoogleMap-Routes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sha-GoogleMap-Routes
  
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Alamofire'
  pod 'SwiftyJSON'

end
